[package]
name = "plonky2-mobile"
version = "0.1.0"
edition = "2024"

[lib]
name = "mopro_bindings"
crate-type = ["lib", "cdylib", "staticlib"]

[[bin]]
name = "ios"

[[bin]]
name = "android"

[[bin]]
name = "compile_fibonacci_circuit"

[[bin]]
name = "compile_sha256_circuit"

[dependencies]
uniffi = "0.28.0"
mopro-ffi = "0.3.1"
thiserror = "2.0.3"
num-bigint = "0.4.6"
plonky2 = "1.0.2"
plonky2_circuits = { path = "../../plonky2" }
plonky2_u32 = { git = "https://github.com/alxkzmn/plonky2-u32", rev = "167d8a6" }

[build-dependencies]
uniffi = { version = "0.28.0", features = ["build"] }

[dev-dependencies]
uniffi = { version = "0.28.0", features = ["bindgen-tests"] }

[workspace]